# Selection Colors
selection_foreground     #ffffff
selection_background     #ff94df

# Window border Colors
active_border_color      #8ec07c
inactive_border_color    #665c54

# Kitty tabs colors 
active_tab_foreground    #ebdbb2
active_tab_background    #458588
inactive_tab_foreground  #ebdbb2
inactive_tab_background  #8ec07c

# Basic color
background               #0f111a
foreground               #eff1f5

# 16 main colors
color0                   #171421
color1                   #CF1E60
color2                   #FF81DC
color3                   #52AF56
color4                   #346DB4
color5                   #952AFF
color6                   #2ADCF7
color7                   #D0CFCC
color8                   #5E5C64
color9                   #E65689
color10                  #FFC4E4
color11                  #65F487
color12                  #4597FB
color13                  #DA74FF
color14                  #95F1FF
color15                  #FFFFFF

# Cursor colors
cursor                   #bdae93
cursor_text_color        #665c54

# Url color
url_color                #458588
